import type { CSSProperties } from "react";

const bahrainTheme = {
  family: "editorial-premium",
  background: "bg-depth",
  color: {
    bg: "#07080b",
    bgTop: "#130308",
    bgDeep: "#030406",
    foreground: "#fcfcfd",
    foregroundSoft: "#ebe6e8",
    muted: "#b4a6ab",
    primary: "#c91f3f",
    primarySoft: "#f04f6c",
    primaryStrong: "#ff3158",
    secondary: "#d5ab56",
    surface: "rgba(18, 17, 21, 0.78)",
    surfaceStrong: "rgba(30, 15, 20, 0.92)",
    surfaceAccent: "rgba(94, 17, 35, 0.82)",
    surfaceMedia: "rgba(37, 20, 28, 0.92)",
    borderSoft: "rgba(255, 255, 255, 0.12)",
    borderStrong: "rgba(255, 255, 255, 0.2)",
    gridLine: "rgba(255, 255, 255, 0.06)",
    glow: "rgba(201, 31, 63, 0.4)",
  },
  chrome: {
    headerSurface: "rgba(13, 14, 17, 0.78)",
    headerBorder: "rgba(255, 255, 255, 0.12)",
    headerShadow: "0 24px 70px rgba(0, 0, 0, 0.42)",
    footerSurface: "rgba(13, 13, 16, 0.88)",
    footerBorder: "rgba(255, 255, 255, 0.1)",
  },
  component: {
    cardSurface: "rgba(19, 16, 21, 0.8)",
    cardSurfaceStrong: "rgba(34, 15, 22, 0.92)",
    cardBorder: "rgba(255, 255, 255, 0.12)",
    mediaSurface: "linear-gradient(180deg, rgba(59, 13, 24, 0.95), rgba(13, 13, 16, 0.96))",
    buttonBg: "linear-gradient(135deg, #ff355c 0%, #bc1738 55%, #88172e 100%)",
    buttonFg: "#ffffff",
    buttonBorder: "rgba(255, 255, 255, 0.18)",
  },
  layout: {
    containerWidth: "1180px",
    sectionY: "clamp(4rem, 7vw, 6.1rem)",
    sectionYMobile: "clamp(3rem, 8vw, 4rem)",
    containerX: "clamp(1rem, 3vw, 2rem)",
    gridGap: "clamp(1rem, 2vw, 1.4rem)",
    cardPadding: "clamp(1rem, 2vw, 1.4rem)",
  },
  radius: {
    sm: "14px",
    md: "20px",
    lg: "30px",
    xl: "42px",
    pill: "999px",
  },
  shadow: {
    soft: "0 16px 50px rgba(0, 0, 0, 0.18)",
    card: "0 24px 70px rgba(0, 0, 0, 0.28)",
    hero: "0 36px 90px rgba(0, 0, 0, 0.42)",
    glow: "0 0 40px rgba(201, 31, 63, 0.26)",
  },
  type: {
    display: "clamp(2.8rem, 7vw, 5.3rem)",
    heading: "clamp(2rem, 5vw, 3.35rem)",
    subheading: "clamp(1rem, 2vw, 1.18rem)",
    cardTitle: "clamp(1.1rem, 2vw, 1.42rem)",
    bodyLg: "clamp(1.05rem, 2vw, 1.2rem)",
    body: "clamp(0.96rem, 1.4vw, 1.06rem)",
    label: "0.78rem",
    meta: "0.88rem",
    metric: "clamp(1.7rem, 3vw, 2.4rem)",
    metricSecondary: "0.92rem",
    stat: "clamp(1.18rem, 2vw, 1.5rem)",
  },
  motion: {
    fast: "220ms",
    base: "420ms",
    slow: "760ms",
    loop: "5200ms",
  },
} as const;

type ThemeVars = Record<`--${string}`, string>;

function createThemeVariables() {
  const vars: ThemeVars = {
    "--color-bg": bahrainTheme.color.bg,
    "--color-bg-top": bahrainTheme.color.bgTop,
    "--color-bg-deep": bahrainTheme.color.bgDeep,
    "--color-foreground": bahrainTheme.color.foreground,
    "--color-foreground-soft": bahrainTheme.color.foregroundSoft,
    "--color-muted": bahrainTheme.color.muted,
    "--color-primary": bahrainTheme.color.primary,
    "--color-primary-soft": bahrainTheme.color.primarySoft,
    "--color-primary-strong": bahrainTheme.color.primaryStrong,
    "--color-secondary": bahrainTheme.color.secondary,
    "--color-surface": bahrainTheme.color.surface,
    "--color-surface-strong": bahrainTheme.color.surfaceStrong,
    "--color-surface-accent": bahrainTheme.color.surfaceAccent,
    "--color-surface-media": bahrainTheme.color.surfaceMedia,
    "--color-border-soft": bahrainTheme.color.borderSoft,
    "--color-border-strong": bahrainTheme.color.borderStrong,
    "--color-grid-line": bahrainTheme.color.gridLine,
    "--color-glow": bahrainTheme.color.glow,
    "--header-surface": bahrainTheme.chrome.headerSurface,
    "--header-border": bahrainTheme.chrome.headerBorder,
    "--header-shadow": bahrainTheme.chrome.headerShadow,
    "--footer-surface": bahrainTheme.chrome.footerSurface,
    "--footer-border": bahrainTheme.chrome.footerBorder,
    "--card-surface": bahrainTheme.component.cardSurface,
    "--card-surface-strong": bahrainTheme.component.cardSurfaceStrong,
    "--card-border": bahrainTheme.component.cardBorder,
    "--media-surface": bahrainTheme.component.mediaSurface,
    "--button-bg": bahrainTheme.component.buttonBg,
    "--button-fg": bahrainTheme.component.buttonFg,
    "--button-border": bahrainTheme.component.buttonBorder,
    "--container-width": bahrainTheme.layout.containerWidth,
    "--section-y": bahrainTheme.layout.sectionY,
    "--section-y-mobile": bahrainTheme.layout.sectionYMobile,
    "--container-x": bahrainTheme.layout.containerX,
    "--grid-gap": bahrainTheme.layout.gridGap,
    "--card-padding": bahrainTheme.layout.cardPadding,
    "--radius-sm": bahrainTheme.radius.sm,
    "--radius-md": bahrainTheme.radius.md,
    "--radius-lg": bahrainTheme.radius.lg,
    "--radius-xl": bahrainTheme.radius.xl,
    "--radius-pill": bahrainTheme.radius.pill,
    "--shadow-soft": bahrainTheme.shadow.soft,
    "--shadow-card": bahrainTheme.shadow.card,
    "--shadow-hero": bahrainTheme.shadow.hero,
    "--shadow-glow": bahrainTheme.shadow.glow,
    "--display-role": bahrainTheme.type.display,
    "--heading-role": bahrainTheme.type.heading,
    "--subheading-role": bahrainTheme.type.subheading,
    "--card-title-role": bahrainTheme.type.cardTitle,
    "--body-lg-role": bahrainTheme.type.bodyLg,
    "--body-role": bahrainTheme.type.body,
    "--label-role": bahrainTheme.type.label,
    "--meta-role": bahrainTheme.type.meta,
    "--metric-role": bahrainTheme.type.metric,
    "--metric-secondary-role": bahrainTheme.type.metricSecondary,
    "--stat-role": bahrainTheme.type.stat,
    "--motion-fast": bahrainTheme.motion.fast,
    "--motion-base": bahrainTheme.motion.base,
    "--motion-slow": bahrainTheme.motion.slow,
    "--motion-loop": bahrainTheme.motion.loop,
  };

  return vars;
}

export const bahrainThemeVars = createThemeVariables() as CSSProperties;

export { bahrainTheme };
